### ISSUE TITLE
Add README.md and fix build

### ISSUE THREAD

**Issue by discordier** [contao-community-alliance/dc-general-contao-frontend#17]
Please add a `README.md` and fix the travis build.

**Comment by richardhj** [comment]
README added in 8b92fdb5b4891ac0d5e3e8047ab03a32502bd790.

**Comment by richardhj** [comment]
Build runs without error.

**Comment by richardhj** [comment]
I cant get over some build errors.
The phpcs task fails because of some warnings I cannot get rid of.
@discordier?
https://travis-ci.org/contao-community-alliance/dc-general-contao-frontend/builds/515703265
