### ISSUE TITLE
Request new Event for manipulationg the widget output

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/dc-general-contao-frontend#18]
Is it possible to add a new Event here: 
https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/feature/contao4/src/View/WidgetManager.php#L150

Reasone is, that i want to add some JS code for the fields to add some features/functions like TinyMce or the Pickers ;)
Since the FE has custom JS code or use jQuery or other js frameworks this would be the best way to handle this. 

What does the other thing of this?

Event could be named like: ManipulateWidgetHtml or GenerateWidgetHtml or ParseWidget.

**Comment by discordier** [comment]
Any reason why `BuildWidgetEvent` does not work? I mean, the tinyMCE and the like are built with that one.

**Comment by baumannsven** [comment]
@discordier The tinyMCE where not implement via event. It is implement directly with the manager for widgets.
See: https://github.com/contao-community-alliance/dc-general/blob/6b116239b86f5e69bb02bdce9ee292918cf7aa40/src/Contao/View/Contao2BackendView/ContaoWidgetManager.php#L392

**Comment by richardhj** [comment]
Can you utilize the `BuildWidgetEvent` nonetheless?

**Comment by zonky2** [comment]
@stefanheimes use the permalink - you mean? https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/7a29cdb4de6ef113c9d448130e9ceef360c14b42/src/View/WidgetManager.php#L150

BuildWidgetEvent FE: https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/7a29cdb4de6ef113c9d448130e9ceef360c14b42/src/Event/BuildWidgetEvent.php

**Comment by zonky2** [comment]
@stefanheimes I checked the `BuildWidgetEvent` FE - works fine

in V 2.2 we add the possibility to choose your own template
