### ISSUE TITLE
Remove transitive dependency to metamodels/frontend-editing

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dc-general-contao-frontend#20]
https://github.com/contao-community-alliance/dc-general-contao-frontend/blob/e7788e37e1e85cb35bf3b704b18d32cb313c3112/src/View/ActionHandler/CreateVariantHandler.php#L136-L139

This package has a transitive dependency on the MM-FEE that needs to be removed.

**Comment by discordier** [comment]
Shees, where does that come from... nice catch.

**Comment by discordier** [comment]
On a second thought, what does it do there?
As I understand it, it makes dcg-fee completely unusable for any non MM data provider?

**Comment by richardhj** [comment]
I guess we can just remove the quoted lines and we are fine, aren't we?

Hm no... Does the DCG have a native function to generate variants? Otherwise, this needs to be moved to the MM-FEE package.

**Comment by discordier** [comment]
Ah, so this is for variant handling.
Yes this needs to get moved to mm-fee then. We have similar functionality in the MM core for variants, dcg does not know about them as they are merely a custom parent child relationship.

**Comment by richardhj** [comment]
Fixed.
