### ISSUE TITLE
Use "disabled" instead of "readonly" for checkboxes and select menus

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dc-general-contao-frontend#22]
When a readonly-attribute is rendered, it has the `readonly` attribute. The correct attribute would be the `disabled` attribute for checkboxes and select menus.

Is this the same (wrong) behavior in the dcg @baumannsven ?

**Comment by zonky2** [comment]
related with https://github.com/MetaModels/core/issues/567

**Comment by richardhj** [comment]
Closing in favor of #23
